---
title: "104-plot-pca-175"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Creating a two-panel PCA with proportion variance and clearer symbols

```{r prep, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggpubr)
load(file="outputs/103/pca-meta.rda")
cov<-read_tsv("./outputs/102/175cov.cov", col_names=FALSE) %>% as.matrix()
```

###Thanks Eric A. for this handy function!!!
```{r, warning=FALSE, message=FALSE}
#' @param samples character vector with the individuals IDs in the order in which
#' they were passed in the bamlist to angsd.
#' @param cov covariance matrix
covar2pcs <- function(samples, cov) {
  
  
  eig <- eigen(cov, symm = TRUE)
  PC <- as.data.frame(eig$vectors) %>%
    as_tibble() %>%
    setNames(sprintf("PC-%02d", 1:ncol(.)))
  
  samtib <- tibble(sample = samples)
  
  list(
    PCs = bind_cols(samtib, PC),
    eigevalues = eig$values
  )
}
```

Shameless copying from Eric A. again.
```{r, warning=FALSE, message=FALSE}
pca <- covar2pcs(pca_meta$vcf_name, cov)

pca_long <- pca$PCs %>%
  tidyr::gather(., key = "PC", "val", -sample)

# then expand a grid of the possible comparisons (ordered)
expg <- expand.grid(sample = pca$PCs$sample,
                    PCx = sprintf("PC-%02d", 1:6),
                    PCy = sprintf("PC-%02d", 1:6),
                    stringsAsFactors = FALSE) %>%
  tibble::as_tibble()

# then left join the pca results onto that
pca_pairs <- dplyr::left_join(expg, pca_long, by = c("sample", "PCx" = "PC")) %>%
  dplyr::rename(val_x = val) %>%
  dplyr::left_join(pca_long, by = c("sample", "PCy" = "PC")) %>%
  dplyr::rename(val_y = val)

pp_meta <- pca_pairs %>%   # just keep the first 6 PCs around
  left_join(., pca_meta, by = c("sample" = "vcf_name")) %>%
  mutate(group = Region)  # put a group column in there

#I'm adding in some different names, for "Population"
pp_meta <- pp_meta %>% mutate(Population = ifelse(Site == "StormyLake", "Kenai",
                                           ifelse(Site == "TinyLake", "Kenai",
                                           ifelse(Site %in% c("Tyonek", "ShellLake", "AndersonLake",
                                                              "OtterLake", "BulchitnaLake",
                                                              "AlexanderLake",
                                                              "YentnaIndianCreek", "DeshkaRiver"), 
                                                              "AnchorageBowl",
                                            Site)
)))

pp_meta$Population<- factor(pp_meta$Population, levels=c("AntlinRiver","EagleLake",
                                                         "MintoFlats","YukonFlats",
                                                         "Fairbanks", "AnchorageBowl",
                                                         "Kenai","LakeClark","LakeNerka",
                                                         "NorthSlope","Selawik"))


# now, that has the first 6 PCs in it.  If we want to focus on the just the
# first 3, we could do 
npc <- 3
pp_meta2 <- pp_meta %>%
  filter( (PCx %in% sprintf("PC-%02d", 1:npc)) & 
            (PCy %in% sprintf("PC-%02d", 1:npc)) )

ggplot(pp_meta2, aes(x = val_x, y = val_y, fill = group)) +
  geom_point(pch = 21, size = 2) +
  scale_fill_discrete(na.value = "white") + 
  facet_grid(PCy ~ PCx, scales = "free")


```
## Reordering for plotting

```{r reorder, warning=FALSE, message=FALSE}
pp_shape<-pp_meta2

#Reordering for plotting
pp_shape$Region<- factor(pp_shape$Region, levels=c("Southeast","Midwest","Interior","Southwest", "Northwest","North","Southcentral"))        

ggplot(pp_shape, aes(x = val_x, y = val_y, fill = Region, shape= Region)) +
  geom_point(size = 2) +
  scale_fill_discrete(na.value = "white") + 
  facet_grid(PCy ~ PCx, scales = "free")+
  theme_bw()+
  theme(panel.grid=element_blank())+
  xlab("PC X")+
  ylab("PC Y")+
  scale_shape_manual(values=c(24,21,21,22,22,22,23))
```  



## Computing Proportion of Variance
```{r, message=FALSE, warning=FALSE}
eig <- eigen(cov, symm = TRUE)
var<-eig$values/sum(eig$values)
cumvar<-cumsum(eig$values)/sum(eig$values)

head(var)
head(cumvar)

sub12<-pp_shape %>% filter( (PCx =="PC-01") & (PCy =="PC-02") )
ggplot(sub12, aes(x = val_x, y = val_y, fill = Region, shape= Region)) +
  geom_point(size = 2) +
  scale_fill_discrete(na.value = "white") + 
  theme_bw()+
  theme(panel.grid=element_blank())+
  xlab(paste("PC1", " ", round((100*var[1]),2), "%", sep = ""))+
  ylab(paste("PC2", " ", round((100*var[2]),2), "%", sep = ""))+
  scale_shape_manual(values=c(24,21,21,22,22,22,23))
```

#Now to recolor and reshape

But first, to compute centroids....
```{r centre, warning=FALSE, message=FALSE}
library(ggrepel)
centers<-sub12 %>% group_by(Population) %>% mutate(MeanX=mean(val_x), MeanY=mean(val_y)) %>% select(Population, MeanX, MeanY) %>% unique()

ggplot()+
  geom_text_repel(data=centers, aes(x=MeanX, y=MeanY, label=Population))

```

```{r 12, warning=FALSE, message=FALSE}
pc12<-ggplot()+
  geom_point(data=sub12, aes(x = val_x, y = val_y, color=Region), size=2, alpha=0.75)+
  geom_text_repel(data=centers, aes(x=MeanX, y=MeanY, label=Population), fontface='bold', size=3)+
  scale_fill_brewer(palette="Set1")+
  theme_bw()+
  theme(panel.grid=element_blank())+
  xlab(paste("PC1", " ", round((100*var[1]),2), "%", sep = ""))+
  ylab(paste("PC2", " ", round((100*var[2]),2), "%", sep = ""))+
  theme(legend.position = "")

pc12

ggsave("outputs/104/pc1-2.pdf")

```

```{r 13, warning=FALSE, message=FALSE}
sub13<-pp_shape %>% filter( (PCx =="PC-01") & (PCy =="PC-03") )

centers13<-sub13 %>% group_by(Population) %>% mutate(MeanX=mean(val_x), MeanY=mean(val_y)) %>% select(Population, MeanX, MeanY) %>% unique()

pc13<-ggplot()+
  geom_point(data=sub13, aes(x = val_x, y = val_y, color=Region), size=2, alpha=0.75)+
  geom_text_repel(data=centers13, aes(x=MeanX, y=MeanY, label=Population), fontface='bold', size=3)+
  scale_fill_brewer(palette="Set1")+
  theme_bw()+
  theme(panel.grid=element_blank())+
  xlab(paste("PC1", " ", round((100*var[1]),2), "%", sep = ""))+
  ylab(paste("PC3", " ", round((100*var[3]),2), "%", sep = ""))+
  theme(legend.position = "")

pc13

ggsave("outputs/104/pc1-3.pdf")

```

#Combine
```{r combine, warning=FALSE, message=FALSE}
library("ggpubr")
ggarrange(pc12, pc13, ncol = 2)
ggsave("outputs/104/combinedPCs.pdf")
```

