---
title: "1500-358-phylogeny"
author: "Mac Campbell"
date: "October 20, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
library(adegenet)
library(vcfR)
library(ggtree)
library(ape)
library(ggpubr)
library(gridExtra)
library(phangorn)
library(viridis)
library(grid)
```


## Making a tree

```{r}
bamlist<-read_tsv("bamlists/358.bamlist", col_names=c("String"))
meta<-read_csv("metadata/358.csv")
meta<-left_join(bamlist, meta)
```

```{r}
sub<-meta %>% select(`RAD identifier`, String, Region, Site) %>% mutate(Label=paste0(Region,"-",Site)) 
write_tsv(select(sub,`RAD identifier`), "metadata/358-samples.tsv", col_names = FALSE)
```

Moving locally...
```{sh, eval=FALSE}
mv 358-phylo.tfam plink.tfam
mv 358-phylo.tped plink.tped

plink --tped plink.tped --tfam plink.tfam  --out binary --recode --allow-extra-chr --noweb
plink --ped binary.ped --map binary.map --recode vcf --allow-extra-chr -out recode
bcftools +prune -l 0.9 -w 10000 recode.vcf  -Ov -o recode.prune.vcf
bcftools reheader --samples ../../metadata/358-samples.tsv -o recode.prune.reheadered.vcf recode.prune.vcf
source activate py2; ~/github/mccloud-rrt/vcf2phylip.py -i recode.prune.reheadered.vcf; conda deactivate;
 ~/github/mccloud-rrt/103-remove-invariant.py -p recode.prune.reheadered.min4.phy -o recode.prune.reheadered.min4.asc.phy
```


### PCA


Read in recode.prune.reheadered.vcf

```{r}
vcf<-read.vcfR(file="outputs/1500/recode.prune.reheadered.vcf")
genind<-vcfR2genind(vcf)
genind@pop<-as.factor(paste0(sub$Region,"-",sub$Site))
```




```{r}
gen<-genind
X <- tab(gen, NA.method="mean")

pca1 <- dudi.pca(X,scannf=FALSE,scale=FALSE,nf=3)
plot(pca1$li)
```

```{r}
pcdf<-as_tibble(pca1$l1) %>% rename(PC1=RS1, PC2=RS2, PC3=RS3)
pcdf$Site<-pop(gen)
pcdf<-pcdf %>% separate(Site, into=c("Region","Site"))

pcdf$Region<- factor(pcdf$Region, levels=c("Southeast","Southcentral", "Southwest", "Interior", "Northwest",
                                                   "North","Midwest"))        

eigens<-as_tibble(pca1$eig) %>% rename(Eigen=value) %>% mutate(Porportion=Eigen/sum(Eigen)*100)

ggplot(pcdf)+geom_point(aes(x=PC1, y=PC1, fill=Site, shape=Region), alpha=0.75, size=2)+
  theme_bw()+
  theme(panel.grid=element_blank()) +
  theme(axis.title = element_text(face="bold")) +
  theme(legend.title = element_text(face="bold")) + 
  scale_shape_manual(values=c(24,21,22,22,22,22,23)) + 
  guides(fill = guide_legend(override.aes=list(shape=22))) +
  theme(legend.position = "") +
  theme(plot.title = element_text(face="bold", size=16))

ggplot(pcdf)+geom_point(aes(x=PC2, y=PC2, fill=Site, shape=Region), alpha=0.75, size=2)+
  theme_bw()+
  theme(panel.grid=element_blank()) +
  theme(axis.title = element_text(face="bold")) +
  theme(legend.title = element_text(face="bold")) +
  scale_shape_manual(values=c(24,21,22,22,22,22,23)) +   
  guides(fill = guide_legend(override.aes=list(shape=22))) +
  theme(legend.position = "") +
  theme(plot.title = element_text(face="bold", size=16))

```

```{r}
p12<-ggplot(pcdf)+geom_point(aes(x=PC1, y=PC2, fill=Site, shape=Region), alpha=0.75, size=2)+
  xlab(paste0("PC1 ", round(eigens$Porportion[1],2),"%")) +
  ylab(paste0("PC2 ", round(eigens$Porportion[2],2),"%")) +
  theme_bw()+
  theme(panel.grid=element_blank()) +
  theme(axis.title = element_text(face="bold")) +
  theme(legend.title = element_text(face="bold")) +
  scale_shape_manual(values=c(24,21,22,22,22,22,23)) +   
  guides(fill = guide_legend(override.aes=list(shape=22))) +
 # theme(legend.position = "") +
  ggtitle("A")+
  theme(plot.title = element_text(face="bold", size=16))
p12

ggsave("outputs/1500/pc12.pdf", width =11, height=8)
```

### Tree
```{sh, eval=FALSE}
iqtree -s recode.prune.reheadered.min4.asc.phy -st DNA -m GTR+G4+F+ASC -bb 1000 -alrt 1000
```

```{r}
ml<-read.tree("outputs/1500/recode.prune.reheadered.min4.asc.phy.contree")
t2<-as.polytomy(midpoint(ml), feature='node.label', fun=function(x) as.numeric(x) < 75)

tt2<-ggtree(t2)  %<+% sub  
tt2$data$Region<-factor(tt2$data$Region, levels=c("Southeast","Southcentral", "Southwest", "Interior", "Northwest",
                                                   "North","Midwest"))       

tt2 + geom_tiplab(aes(label=Site, color=Region), align=TRUE, size=1) +
    geom_nodelab(aes(label=node)) +
    xlim(0,.75)
ggsave("outputs/1500/358-rectangular-tree.pdf", height=20, width=10)
```
```{r, eval=FALSE}
mlt<-ggtree(read.tree("outputs/1500/recode.prune.reheadered.min4.asc.phy.contree"), layout = "daylight") %<+% sub 
save(mlt,file="outputs/1500/mlt.rda")
```

```{r}
mlt$data$Region<-factor(mlt$data$Region, levels=c("Southeast","Southcentral", "Southwest", "Interior", "Northwest",
                                                   "North","Midwest"))        

d <- mlt$data
d <- d[!d$isTip,]
d$label <- as.numeric(d$label)
d <- d[d$label > 90,]

e <- mlt$data
e <- e[!e$isTip,]
e$label <- as.numeric(e$label)
e <- e[e$label < 90,]
e <- e[e$label > 75,]

t1 <- mlt + 
    geom_point(data=e,  color="gray50", cex=3, alpha=0.75) +
    geom_point(data=d,  color="black", cex=3, alpha=0.75) +
    geom_tippoint(aes(shape=Region, fill=Region), cex=4) +
    scale_shape_manual(values=c(24,21,22,22,22,22,23)) 
t1
ggsave("outputs/1500/358-daylight-tree.pdf", height=8, width=9)

```

```{r}
mlt + geom_nodelab(aes(label=node))
ggsave("outputs/1500/358-daylight-node-labels.pdf", height=8, width=9)

```

```{r}
collapse(tt2, node=501) %>% open_tree(180) + 
  geom_tippoint(aes(shape=Region, fill=Site), cex=3) +
  scale_shape_manual(values=c(24,21,22,22,22,22,23)) +
  theme(legend.position = "")
```


## Pruning taxa

```{r, eval=FALSE}
sc<-meta %>% filter(Region=="Southcentral")
pruned<-drop.tip(ml,ml$tip.label[-match(sc$`RAD identifier`, ml$tip.label)])
p<-ggtree(pruned, layout = "daylight")
save(p, file="outputs/1500/pruned-tree.rda")
```

```{r}
load("outputs/1500/pruned-tree.rda")

p
```
Set colors
```{r}
cols=viridis(length(unique(sc$Site))+1, option = "turbo")

```

```{r}
kenai<-meta %>% filter(Region=="Southcentral") %>% filter(Site %in% c("StormyLake","TinyLake"))
ktree<-drop.tip(ml,ml$tip.label[-match(kenai$`RAD identifier`, ml$tip.label)])
k<-ggtree(ktree, layout = "daylight")
save(k, file="outputs/1500/k-pruned-tree.rda")
```

```{r}
load("outputs/1500/k-pruned-tree.rda")
kt<-k %<+% sub 
kt$data$Bootstrap<-as.numeric(kt$data$label)

d <- kt$data
d <- d[!d$isTip,]
d$label <- as.numeric(d$label)
d <- d[d$label > 90,]

e <- kt$data
e <- e[!e$isTip,]
e$label <- as.numeric(e$label)
e <- e[e$label < 90,]
e <- e[e$label > 75,]


figa<-kt +
  geom_point(data=e,  color="gray50", cex=3, alpha=0.75) +
  geom_point(data=d,  color="black", cex=3, alpha=0.75) +
  geom_tippoint(aes(shape=Region, fill=Site), cex=4) +
  scale_shape_manual(values=c(21), guide=FALSE) +
  scale_fill_manual(values=cols[2:3]) +
  guides(fill = guide_legend(override.aes=list(shape=21))) 
  
figa
```



```{r}
anc<-meta %>% filter(Region=="Southcentral") %>% filter(!Site %in% c("StormyLake","TinyLake"))
atree<-drop.tip(ml,ml$tip.label[-match(anc$`RAD identifier`, ml$tip.label)])
a<-ggtree(atree, layout = "daylight")
save(a, file="outputs/1500/a-pruned-tree.rda")
```

```{r}
load("outputs/1500/a-pruned-tree.rda")
at<-a %<+% sub 
at$data$Bootstrap<-as.numeric(at$data$label)

d <- at$data
d <- d[!d$isTip,]
d$label <- as.numeric(d$label)
d <- d[d$label > 90,]

e <- at$data
e <- e[!e$isTip,]
e$label <- as.numeric(e$label)
e <- e[e$label < 90,]
e <- e[e$label > 75,]


figb<-at +
  geom_point(data=e,  color="gray50", cex=3, alpha=0.75) +
  geom_point(data=d,  color="black", cex=3, alpha=0.75) +
  geom_tippoint(aes(shape=Region, fill=Site), cex=4) +
  scale_shape_manual(values=c(21), guide=FALSE) +
  scale_fill_manual(values=cols[3:13]) +
  guides(fill = guide_legend(override.aes=list(shape=21))) 
  
```


Plot!
```{r}
blank <- grid.rect(gp=gpar(col="white"))
```

```{r}
ggarrange(t1, arrangeGrob(figb, arrangeGrob(blank,figa,blank, nrow=3, heights = c(1,3,1)), ncol=2, 
                          widths=c(2,1)), nrow=2, heights=c(1,.7))
ggsave("outputs/1500/individual-trees.pdf", width=12, height=15)

```
