---
title: "1700-basic-map"
author: "Mac Campbell"
date: "4/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=TRUE, message=FALSE)
```

```{r}
library(tidyverse)
library(maps)
library(raster)
library(viridis)
library(ggrepel)
library(scales)
```


#Samples
See 1200 for origins of samples:

```{r}
samples<-read_csv("metadata/358-edited.csv")
locs<- samples %>% group_by(Region, Site) %>% mutate(newx=mean(Longitude), newy=mean(Latitude)) %>% group_by(Region, Site, newx, newy) %>%
  summarize(Count=n())

locs$Region<-factor(locs$Region, levels=c("Southeast","Southcentral", "Southwest", "Interior", "Northwest",
                                                   "North","Midwest"))        

```
```{r}
ggplot(locs) +
  geom_point(aes(x=newx, y=newy, fill=Region, shape=Region), alpha=0.75) +
    scale_shape_manual(values=c(24,21,22,22,22,22,23)) +
  geom_text_repel(data=locs %>% filter(Region != "Southcentral"), aes(x=newx, y=newy, label=Site)) +
  theme(legend.position = "none")

```

Get colors.    
```{r}
locs$Region
```

```{r}
codes<-hue_pal()(length(unique(locs$Region)))
show_col(codes)
```

#Load in base raster.

```{r}


#  coord_fixed(1.3, xlim=c(-180,-90), ylim=c(45,80))

domain <- c(min(-180), max(-90), min(45), max(80))

# here eric implements something and I copy it
tidy_subset <- function(x, longlat) {
  x@data$id <- rownames(x@data)
  x.f <- broom::tidy(x) %>%
    dplyr::left_join(., x@data, by = "id") %>%
    dplyr::tbl_df() %>%
    filter(long > longlat[1],
           long < longlat[2],
           lat > longlat[3],
           lat < longlat[4])
}

```



```{r, eval=FALSE}
nat.earth<-stack("~/github/mccloud-rrt/outputs/1000/NE2_HR_LC_SR_W_DR/NE2_HR_LC_SR_W_DR.tif")

nat.crop <- crop(nat.earth, y=extent(domain))

rast.table <- data.frame(xyFromCell(nat.crop, 1:ncell(nat.crop)),
                         getValues(nat.crop/255)) #originally 255


rast.table$rgb <- with(rast.table, rgb(NE2_HR_LC_SR_W_DR.1,
                                       NE2_HR_LC_SR_W_DR.2,
                                       NE2_HR_LC_SR_W_DR.3,
                                       1))

save(rast.table, file="outputs/1700/rast.table.rda")
```

```{r}
load("outputs/1700/rast.table.rda")
```


```{r}
ggplot() +
  geom_raster(data = rast.table, mapping = aes(x = x, y = y), fill = rast.table$rgb, interpolate = TRUE)  +
  geom_point(data=locs, aes(x=newx, y=newy, fill=Region, shape=Region), cex=3, alpha=0.75) +
  scale_shape_manual(values=c(24,21,22,22,22,22,23)) +
  geom_text_repel(data=locs %>% filter(Region != "Southcentral"), aes(x=newx, y=newy, label=Site)) +
  theme_bw() +
  theme(panel.grid=element_blank()) +
  xlab("Longitude") +
  ylab("Latitude") +
  coord_fixed(1.3, xlim=c(-180,-90), ylim=c(45,80))  +
  theme(legend.position = "none")

ggsave("outputs/1700/big-map.pdf", width = 8.5, height=11)
```

## Zoom in on SC

```{r}
sc<-locs %>% filter(Region=="Southcentral")
cols=viridis(length(unique(sc$Site))+1, option = "turbo")
```

```{r}
domain <- c(-156, -146, 58, 64)
```


```{r}
nat.earth<-stack("~/github/mccloud-rrt/outputs/1000/NE2_HR_LC_SR_W_DR/NE2_HR_LC_SR_W_DR.tif")

nat.crop <- crop(nat.earth, y=extent(domain))

rast.table <- data.frame(xyFromCell(nat.crop, 1:ncell(nat.crop)),
                         getValues(nat.crop/255)) #originally 255


rast.table$rgb <- with(rast.table, rgb(NE2_HR_LC_SR_W_DR.1,
                                       NE2_HR_LC_SR_W_DR.2,
                                       NE2_HR_LC_SR_W_DR.3,
                                       1))

save(rast.table, file="outputs/1700/rast.table-2.rda")
```

```{r}
sc$Site2<-factor(sc$Site, levels=c("StormyLake","TinyLake",sc$Site[1:7], sc$Site[10:11]))

```

```{r}
ggplot() +
  geom_raster(data = rast.table, mapping = aes(x = x, y = y), fill = rast.table$rgb, interpolate = TRUE)  +
  geom_jitter(data=sc, aes(x=newx, y=newy, size=Count, fill=Site2), pch=21) +
  geom_text_repel(data=sc, aes(x=newx, y=newy, label=Site), max.overlaps = Inf) +
  scale_fill_manual(values=cols) +
  theme_bw() +
  theme(panel.grid = element_blank()) +
  xlab("Longitude") +
  ylab("Latitude") +
  coord_fixed(1.3,xlim=c(-154,-147), ylim=c(59, 63.5)) +
  guides(fill = "none")

ggsave("outputs/1700/southcentral.pdf", width=7, height=5)

```
  
  
  
  geom_point(data=locs, aes(x=newx, y=newy, size=Count, fill=Region, shape=Region), alpha=0.75) +
  scale_shape_manual(values=c(24,21,22,22,22,22,23)) +
  theme_bw() +
  theme(panel.grid=element_blank())+
  
