---
title: "400-pop-gen"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, echo=FALSE, message=FALSE}
library(tidyverse)
library(adegenet)
library(poppr)
library(pegas)
library(genetics)
library(hierfstat)
```

# Let's load in some data!
```{r, warning=FALSE, message=FALSE}

genos<-read_tsv(file="outputs/301/177-vcf.geno.gz", col_names = FALSE)
data <-as_tibble(t(genos[3:179]))
loci <- genos %>% dplyr::select(X1, X2) 
loci$X1<-gsub("\\.","_", loci$X1)
loci$X1<-gsub("_","", loci$X1)

loci<- loci %>% dplyr::mutate(Locus=paste(X1, X2, sep="-"))

# We need to include individual/population names
load("outputs/103/pca-meta.rda")
bams <- read_tsv("bamlists/177.bamlist", col_names = FALSE) %>%
  mutate(vcf_name = str_replace_all(X1, pattern = "^data/|AN1711171/|BK1703222/|_sorted.*$", "")) %>%
  mutate(index = 1:n())
ad_meta <- left_join(bams, pca_meta)

# remove spaces
ad_meta <- ad_meta %>% mutate(Name = paste(gsub(Region, pattern=" ",
                                                   replacement=""), index, sep="_"))
# Separate Kenai
ad_meta <- ad_meta %>% mutate(Population = ifelse(Site == "StormyLake", "Kenai",
                                           ifelse(Site == "TinyLake", "Kenai",
                                           ifelse(Site %in% c("Tyonek", "ShellLake", "AndersonLake",
                                                              "OtterLake", "BulchitnaLake",
                                                              "AlexanderLake",
                                                              "YentnaIndianCreek", "DeshkaRiver"), 
                                                              "AnchorageBowl",
                                            Site)
)))

colnames(data)<-loci$Locus
```

#Make a genind
```{r, warning=FALSE, message=FALSE}
gdf<-as.loci(data[1:500], sep="/", ploidy=2)
genind<-df2genind(gdf, sep="/")
genind@pop<-as.factor(ad_meta$Population)
save(genind, file="outputs/400/genind-sub.rda")
```

#Basic stats
```{r, warning=FALSE, message=FALSE}
popdata<-poppr(genind)
popdata
```

#Fst
```{r, warning=FALSE, message=FALSE}
pairwise.fst(genind)
```

#I like population coord distances 
```{r, warning=FALSE, message=FALSE}

tree1<-aboot(genind, strata=genind@pop, tree="nj",distance="edwards.dist",missing="mean", cutoff=50, sample=1000) 

pdf("outputs/400/tree-sub.pdf")
plot.phylo(tree1, type="unrooted",show.node.label = TRUE)
dev.off()
```
