---
title: "400.1-pop-gen"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Full Dataset
I'm wondering about the MAF

```{r load-data, warning=FALSE, message=FALSE}
library(poppr)
library(adegenet)
library(tidyverse)
load("outputs/400/genind.rda")
```

### Filtering

```{r MAF}

mafdf<-as.data.frame(isPoly(genind, by=c("locus"), thres=(5/100)))
mafdf$Locus<-rownames(mafdf)
mafdf<-as_tibble(mafdf) %>% rename("MAF05"=`isPoly(genind, by = c("locus"), thres = (5/100))`) %>%
  select(Locus, MAF05)
```

What did this do for us?

```{r Echo}
mafdf %>% select(MAF05) %>% group_by(MAF05) %>% summarize(Count=n())
```

Let's subset this thing.

```{r subset, warning=FALSE, message=FALSE}
mafLoci<- mafdf %>% filter(MAF05=="TRUE")

genMaf<-genind[loc=mafLoci$Locus]
save(genMaf, file="outputs/400/genMaf.rda")
```

## Filtered dataset
```{r stats, warning=FALSE}
poppr(genMaf)
```


```{r clusters, warning=FALSE}
grp <- find.clusters(genMaf, max.n.clust = 30, n.pca=95, n.clust = 7)
assign<-dapc(genMaf, n.pca=95, var.contrib = TRUE, n.da=length(levels(grp$grp))-1, pop=grp$grp)

table.value(table(assign$assign, pop(genMaf)), col.lab=levels(pop(genMaf)))
df<-as.data.frame(table(assign$assign, pop(genMaf)), col.lab=levels(pop(genMaf))) %>% filter(Freq > 0)

df$Var2<- factor(df$Var2, levels=c("AntlinRiver","EagleLake", "AnchorageBowl", "Kenai",
                                       "Fairbanks","MintoFlats","YukonFlats", "Selawik",
                                       "NorthSlope","LakeClark", "LakeNerka"))        
ggplot(df, aes(Var1, Var2))+
  theme(axis.title.y = element_text(size = rel(2)))+
  theme(axis.title.x = element_text(size = rel(2)))+
  theme(axis.text.x = element_text(angle = 90))+
  labs(x="\nInferred Group", y="Sampling Location\n")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  theme(text=element_text(family='Times'))+
  theme(axis.text.x= element_text(face="bold", size=10, vjust = 0.5))+
  theme(axis.text.y= element_text(face="bold", size=10))+
  geom_point(aes(x=Var1, y=Var2, size=Freq))+
  scale_size_area(limits=c(1,50), breaks=c(1,5,10,25))+
  labs(size="Number\nof Individuals")
```

### Tree

```{r tree, warning=FALSE, message=FALSE}
library(ape)
tree1<-aboot(genMaf, strata=genMaf@pop, tree="nj",distance="edwards.dist",missing="mean", cutoff=50, sample=1000) 

plot.phylo(tree1, type="unrooted",show.node.label = TRUE)
```